const express=require('express'),helmet=require('helmet'),cors=require('cors'),compression=require('compression'),morgan=require('morgan'),cookieParser=require('cookie-parser');
const config=require('./config/env'); const {globalLimiter}=require('./middleware/rateLimit'); const {auth,roles}=require('./middleware/auth'); const {notFound,errorHandler}=require('./middleware/error');
const app=express();
app.set('trust proxy',1); app.use(helmet()); app.use(cors({origin:(origin,cb)=>{if(!origin||config.corsOrigins.includes('*')||config.corsOrigins.includes(origin))return cb(null,true);cb(new Error('CORS origin not allowed'));},credentials:true})); app.use(compression()); app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true,limit:'2mb'})); app.use(cookieParser()); app.use(morgan(config.nodeEnv==='production'?'combined':'dev')); app.use(globalLimiter);
app.get('/health',async(req,res)=>{try{await require('./config/db').health();res.json({success:true,status:'ok',service:'zenjigo-backend',time:new Date().toISOString()});}catch(e){res.status(503).json({success:false,status:'unhealthy',message:e.message});}});
const p=config.apiPrefix;
app.use(`${p}/auth`,require('./routes/auth.routes'));
app.use(`${p}/rider`,auth,roles('rider'),require('./routes/user.routes'));
app.use(`${p}/rider/rides`,auth,roles('rider'),require('./routes/ride.routes'));
app.use(`${p}/rider/wallet`,auth,roles('rider'),require('./routes/wallet.routes'));
app.use(`${p}/rider/notifications`,auth,roles('rider'),require('./routes/notification.routes'));
app.use(`${p}/rider/chat`,auth,roles('rider'),require('./routes/chat.routes'));
app.use(`${p}/rider`,auth,roles('rider'),require('./routes/extra.routes'));
app.use(`${p}/driver`,require('./routes/driver.public.routes'));
app.use(`${p}/driver`,auth,roles('driver'),require('./routes/driver.routes'));
app.use(`${p}/driver/chat`,auth,roles('driver'),require('./routes/chat.routes'));
app.use(`${p}/driver/notifications`,auth,roles('driver'),require('./routes/notification.routes'));
app.use(`${p}/driver/rides`,auth,roles('driver'),require('./routes/ride.routes'));
app.use(`${p}/admin`,auth,roles('admin'),require('./routes/admin.routes'));
app.use(`${p}/upload`,auth,require('./routes/upload.routes'));
app.use(`${p}/promos`,auth,require('./routes/promo.routes'));
app.use(notFound); app.use(errorHandler); module.exports=app;
